POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name":"Adnan",
    "email":"adnan.irfan@gmail.com",
    "password":"adnan"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "adnan.irfan@gmail.com",
    "password":"adnan"
}

###
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiY2E3NzdmODEtZGRhZS00OWI4LTllM2UtMDM0NTFjYTNhZjNiIiwidXNlcl9uYW1lIjoiQWRuYW4iLCJ1c2VyX2VtYWlsIjoiYWRuYW4uaXJmYW5AZ21haWwuY29tIiwiaWF0IjoxNjMyNzU3Mzg3LCJleHAiOjE2MzI3NTgyODd9.Ifn80flQPWM6Ce1alHO-1Kafj2hnle768MqYGamsZeE


###
GET http://localhost:5000/api/refresh_token

###

DELETE http://localhost:5000/api/auth/refresh_token